@startuml


namespace cpputil {

    class cpputil::io {
        void **readArrayFromFile**(const std::string& filename, Eigen::MatrixXd& M)
        void **readArrayFromFile**(const std::string& filename, Eigen::Tensor<double, 4>& T)
        void **print**(const Eigen::Tensor<double, 4>& T)
    }

    class cpputil::linalg {
        bool **areEqual**(const Eigen::Tensor<double, 4>& M, const Eigen::Tensor<double, 4>& T, double tolerance)
        bool **areEqualEigenvalues**(const Eigen::VectorXd& eigenvalues1, const Eigen::VectorXd& eigenvalues2, double tolerance)
        bool **areEqualEigenvectors**(const Eigen::VectorXd& eigenvectors1, const Eigen::VectorXd& eigenvectors2, double tolerance)
        bool **areEqualSetsOfEigenvectors**(const Eigen::MatrixXd& eigenvectors1, const Eigen::MatrixXd& eigenvectors2, double tolerance)
    }

    class cpputil {
        void **printExecutionTime**(const std::string& method_name, const std::function<void ()>& function)
    }

}

@enduml
